# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckFyabJ4KTatwNXDPJFtqZ8cyK51Jk43
"""

numbers=[10,20,40,100,89,200,150]

max=numbers[0]

for i in numbers:
  if(i>max):
    max=i

print("The maximum number is",max)