# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckFyabJ4KTatwNXDPJFtqZ8cyK51Jk43
"""

# Reverse a String without using slicing[::-1]...

str1=input("Enter a String you want to reverse:")
# now ww have to reverse this.
reversed_str1=""
for i in range(len(str1)-1,-1,-1):
  reversed_str1+=str1[i]

print("Reversed String is:",reversed_str1)